const zines = [
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: false,
    },
    {
        title: "Specialz: Serial Experiments Lain (English)",
        description: "The year was 1945, the Second World War was almost at its end. And the world saw, for the first time, the most powerful weapon of mankind—a weapon so destructive that it could erase a city in a matter of seconds. Families, animals, histories, all that was once full of life were wiped out by the power of technology.",
        image: "imgs/OnegaiZineSpecialzSEL.jpg",
        pdf: "zines/OnegaiZineSpecialzSEL.pdf",
        soon: false,
    },
    {
        title: "A Sign of Affection",
        description: "O anime Yubisaki to Renren (A Sign of Affection em inglês) retrata a vida de Yuki, uma estudante universitária surda, que durante um imprevisto acaba conhecendo o veterano de sua faculdade, Itsuomi, naquele momento se iniciou uma trama que supera qualquer dificuldade.",
        image: "imgs/Site-OnegaiZineExpressASOA.jpg",
        pdf: "zines/Site-OnegaiZineExpressASOA.pdf",
        soon: false,
    },
    {
        title: "Fruits Basket",
        description: "O que será dito sobre o anime Fruits Basket não é nada menos que um tipo de ensaio, como forma de, não entender, mas questionar conceitos já existentes e desabar as paredes da ignorância.",
        image: "imgs/OnegaiZineSpecialzFB.jpg",
        pdf: "zines/OnegaiZineSpecialzFB.pdf",
        soon: false,
    },
    {
        title: "Vinland Saga",
        description: "Por Sukku.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "Dragon Ball Z",
        description: "Por Sena.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "Kaii to Otome to Kamikakushi",
        description: "Por Sukku.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "Your Name",
        description: "Por Féliz.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "Kpop Demon Hunters",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "Jujutsu Kaisen",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "MF Ghost",
        description: "Por Féliz.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "Kokoro Connect",
        description: "Por Magal.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "undefined",
        soon: true,
    },
    {
        title: "Kimetsu no Yaiba",
        description: "Por Melo.",
        image: "imgs/OnegaiZineComingSoon.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
]