const zines = [
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: false,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: false,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: false,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: false,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
    {
        title: "RECO: Edição #1",
        description: "Primeira revista da edição RECO sobre os animes: How I Attended an All-Guy's Mixer, Tamon-kun ima docchi?!, Isekai Ojisan.",
        image: "imgs/Senzine-Reco-1.jpg",
        pdf: "zines/Senzine-Reco-1.pdf",
        soon: true,
    },
]